### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by sites21** [arronhunt/highlightjs-copy#3]
When click on icon, nothing has changed. Why? No errors in console

**Comment by arronhunt** [comment]
@sites21 Can you provide your code or even better a live example? 

- What browser are you using?
- What OS are you using? 
- What version of highlightjs?

**Comment by zhuchunshu** [comment]
> 

After my test, I found that the reason is as follows: navigator.clipboard is invalid in the http state

**Comment by zhuchunshu** [comment]
> @sites21 Can you provide your code or even better a live example?
> 
> * What browser are you using?
> * What OS are you using?
> * What version of highlightjs?

After my test, I found that the reason is as follows: navigator.clipboard is invalid in the http state

**Comment by sites21** [comment]
> @sites21 Can you provide your code or even better a live example?
> 
> * What browser are you using?
> * What OS are you using?
> * What version of highlightjs?

I`m use Gulp for it. And this is periodically doesnt'work

1. Chrome
2. Windows
3. Latest

**Comment by arronhunt** [comment]
Closing this ticket, please re-open if you’re still having issues with later releases.
