### ISSUE TITLE
How to enable on certain code blocks only?

### ISSUE THREAD

**Issue by nitish8090** [arronhunt/highlightjs-copy#37]
Hey buddy, thanks for making this plugin. Love it 🤍, though it misses one of the feature I need.

How to enable or disable on selected elements?
I use `<pre>` `<code>` to show some logs. I don't want a copy button on this block but I need `highlightJS`.

![Screenshot_20241028_154550](https://github.com/user-attachments/assets/4e1d1d15-d8fc-47a8-8724-b2caa79d84ec)

**Comment by arronhunt** [comment]
Thanks @nitish8090, I appreciate it. This is a use case I hadn't considered. I think supporting something like `<code data-disable-copy>` could be a good solution. highlightjs' docs are very minimal for their plugins so I don't know if there's a more common pattern to follow. 

If I have time this week I'll work on this. In the man time, you can use CSS to hide the button on certain elements.

```css
pre.hide-copy-button .hljs-copy-button {
  display: none;
}
```

**Comment by nitish8090** [comment]
Thanks a lot @arronhunt for this. 
And, I found an approach on [highlightjs-line-numbers](https://github.com/wcoder/highlightjs-line-numbers.js) and I'm using this in my project. Here is a PR for that.
