### ISSUE TITLE
Change Inner Text "Copied!" when click copy button

### ISSUE THREAD

**Issue by Llank84** [arronhunt/highlightjs-copy#5]
Hi! I'm Chilean and my native language is Spanish. How can I change text "Copied!" to "Copiado!". 

Thanks

**Comment by arronhunt** [comment]
@Llank84 can you take a look at #7 before I merge to see if this resolves your issue?

**Comment by Llank84** [comment]
@arronhunt it does not work😔. Thanks anyway!
